# Autogenerated wrapper script for dlfcn_win32_jll for i686-w64-mingw32
export libdl

JLLWrappers.@generate_wrapper_header("dlfcn_win32")
JLLWrappers.@declare_library_product(libdl, "libdl.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdl,
        "bin\\libdl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
